name: Build e Deploy Onco  # Opcional, mas ajuda a identificar no painel
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build e Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/onco:backend

      - name: Build e Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/onco:frontend
  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-deploy 
    steps:
      - name: Scan Backend
        uses: aquasecurity/trivy-action@v0.28.0 # Use sempre o 'v' antes da versão
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Resolve o Rate Limit do download
          TRIVY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          TRIVY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          image-ref: 'docker.io/${{ secrets.DOCKERHUB_USERNAME }}/onco:backend'
          format: 'table'
          severity: 'CRITICAL,HIGH'

      - name: Scan Frontend
        uses: aquasecurity/trivy-action@v0.28.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRIVY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          TRIVY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          image-ref: 'docker.io/${{ secrets.DOCKERHUB_USERNAME }}/onco:frontend'
          format: 'table'
          severity: 'CRITICAL,HIGH'